[package]
name = "near-certification-tools"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Lindahl <jacob@near.foundation>"]

[dependencies]
near-sdk = "4.0.0-pre.8"
near-contract-standards = "4.0.0-pre.8"
near-contract-tools = "0.2.0"

[lib]
crate-type = ["cdylib", "lib"]
